In [5]:
import pandas as pd
from numpy.linalg import inv
import numpy as np

df = pd.read_csv('https://bit.ly/3goOAnt', delimiter=",")
df = pd.read_csv('single.csv', delimiter=",")


df

,x,y
0,1,5
1,2,10
2,3,10
3,4,15
4,5,14
5,6,15
6,7,19
7,8,18
8,9,25
9,10,23


In [9]:
x = df.values[:,:-1].flatten()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
df.values[:,:].flatten()

array([ 1,  5,  2, 10,  3, 10,  4, 15,  5, 14,  6, 15,  7, 19,  8, 18,  9,
       25, 10, 23])

In [18]:
x_1 = np.vstack([x,np.ones(len(x))]).T
x_1

array([[ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.],
       [ 4.,  1.],
       [ 5.,  1.],
       [ 6.,  1.],
       [ 7.,  1.],
       [ 8.,  1.],
       [ 9.,  1.],
       [10.,  1.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [20]:
y = df.values[:,-1]
y

array([ 5, 10, 10, 15, 14, 15, 19, 18, 25, 23])

In [23]:
b = inv(x_1.transpose() @ x_1) @ (x_1.transpose() @ y)
b

array([1.93939394, 4.73333333])

In [24]:
y_predict = x_1.dot(b)
y_predict

array([ 6.67272727,  8.61212121, 10.55151515, 12.49090909, 14.43030303,
       16.36969697, 18.30909091, 20.24848485, 22.18787879, 24.12727273])